import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { Calendar as CalendarIcon, Clock, Plus, RefreshCw, AlertCircle, Check, ExternalLink } from 'lucide-react';
import { useTaskStore } from '../../store/useTaskStore';

interface CalendarEvent {
  id: string;
  summary: string;
  start: { dateTime?: string; date?: string };
  end: { dateTime?: string; date?: string };
  htmlLink: string;
}

const ScheduleView = () => {
  const [token, setToken] = useState<string | null>(localStorage.getItem('google_calendar_token'));
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { tasks } = useTaskStore();

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data?.type === 'GOOGLE_AUTH_SUCCESS') {
        const newToken = event.data.token;
        setToken(newToken);
        localStorage.setItem('google_calendar_token', newToken);
        fetchEvents(newToken);
      }
    };
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, []);

  useEffect(() => {
    if (token) {
      fetchEvents(token);
    }
  }, [token]);

  const handleConnect = async () => {
    try {
      const response = await fetch('/api/auth/google/url');
      if (!response.ok) throw new Error('Failed to get auth URL');
      const { url } = await response.json();
      
      const authWindow = window.open(url, 'oauth_popup', 'width=600,height=700');
      if (!authWindow) {
        setError('Please allow popups to connect your calendar.');
      }
    } catch (err) {
      console.error('OAuth error:', err);
      setError('Failed to initiate connection. Please check your configuration.');
    }
  };

  const fetchEvents = async (accessToken: string) => {
    setLoading(true);
    setError(null);
    try {
      const timeMin = new Date().toISOString();
      const timeMax = new Date();
      timeMax.setDate(timeMax.getDate() + 7); // Next 7 days
      
      const response = await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${timeMin}&timeMax=${timeMax.toISOString()}&orderBy=startTime&singleEvents=true&maxResults=20`, {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      });
      
      if (!response.ok) {
        if (response.status === 401) {
          // Token expired
          setToken(null);
          localStorage.removeItem('google_calendar_token');
          throw new Error('Session expired. Please reconnect.');
        }
        throw new Error('Failed to fetch events');
      }
      
      const data = await response.json();
      setEvents(data.items || []);
    } catch (err: any) {
      console.error('Fetch events error:', err);
      setError(err.message || 'Failed to load calendar events');
    } finally {
      setLoading(false);
    }
  };

  const syncTaskToCalendar = async (task: any) => {
    if (!token) return;
    
    try {
      const startTime = new Date();
      startTime.setHours(startTime.getHours() + 1); // Default to 1 hour from now
      
      const endTime = new Date(startTime);
      endTime.setHours(endTime.getHours() + 1); // 1 hour duration
      
      const event = {
        summary: `Study: ${task.text}`,
        description: 'Generated by EgyFlow',
        start: {
          dateTime: startTime.toISOString(),
          timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
        },
        end: {
          dateTime: endTime.toISOString(),
          timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
        },
      };

      const response = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(event)
      });

      if (!response.ok) throw new Error('Failed to create event');
      
      // Refresh events
      fetchEvents(token);
      alert('Task successfully added to your Google Calendar!');
    } catch (err) {
      console.error('Sync error:', err);
      alert('Failed to sync task to calendar.');
    }
  };

  const formatTime = (dateString?: string) => {
    if (!dateString) return 'All Day';
    return new Date(dateString).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const formatDate = (dateString?: string) => {
    if (!dateString) return '';
    return new Date(dateString).toLocaleDateString([], { weekday: 'short', month: 'short', day: 'numeric' });
  };

  return (
    <div className="p-4 md:p-8 space-y-8 pb-24">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-3xl font-bold text-white mb-2">Schedule & Calendar</h2>
          <p className="text-white/60">Sync your study plans with your Google Calendar.</p>
        </div>
        
        {!token ? (
          <button 
            onClick={handleConnect}
            className="bg-white text-black px-6 py-2.5 rounded-xl font-bold hover:bg-gray-100 transition-colors flex items-center gap-2"
          >
            <CalendarIcon size={18} />
            Connect Google Calendar
          </button>
        ) : (
          <div className="flex items-center gap-3">
            <button 
              onClick={() => fetchEvents(token)}
              disabled={loading}
              className="p-2.5 bg-white/5 hover:bg-white/10 rounded-xl text-white/60 hover:text-white transition-colors"
              title="Refresh Calendar"
            >
              <RefreshCw size={18} className={loading ? 'animate-spin' : ''} />
            </button>
            <div className="bg-green-500/10 text-green-400 px-4 py-2.5 rounded-xl border border-green-500/20 flex items-center gap-2 font-medium">
              <Check size={18} />
              Calendar Connected
            </div>
          </div>
        )}
      </div>

      {error && (
        <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-xl flex items-center gap-3">
          <AlertCircle size={20} />
          <p>{error}</p>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Calendar Events Column */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-[#141418] border border-white/5 rounded-2xl p-6">
            <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
              <CalendarIcon className="text-indigo-400" size={24} />
              Upcoming Commitments
            </h3>
            
            {!token ? (
              <div className="text-center py-12 bg-white/5 rounded-xl border border-white/5 border-dashed">
                <CalendarIcon size={48} className="mx-auto mb-4 text-white/20" />
                <h4 className="text-lg font-bold mb-2">No Calendar Connected</h4>
                <p className="text-white/40 max-w-sm mx-auto mb-6">Connect your Google Calendar to see your upcoming events and sync your study tasks.</p>
                <button 
                  onClick={handleConnect}
                  className="bg-indigo-600 hover:bg-indigo-500 text-white px-6 py-2.5 rounded-xl font-bold transition-colors inline-flex items-center gap-2"
                >
                  Connect Now
                </button>
              </div>
            ) : loading && events.length === 0 ? (
              <div className="flex justify-center py-12">
                <RefreshCw size={32} className="animate-spin text-indigo-500" />
              </div>
            ) : events.length === 0 ? (
              <div className="text-center py-12 text-white/40">
                No upcoming events found for the next 7 days.
              </div>
            ) : (
              <div className="space-y-4">
                {events.map((event, index) => {
                  const eventDate = event.start.dateTime || event.start.date;
                  const prevEventDate = index > 0 ? (events[index - 1].start.dateTime || events[index - 1].start.date) : null;
                  
                  const showDateHeader = !prevEventDate || formatDate(eventDate) !== formatDate(prevEventDate);

                  return (
                    <React.Fragment key={event.id}>
                      {showDateHeader && (
                        <div className="pt-4 pb-2">
                          <h4 className="text-sm font-bold text-white/40 uppercase tracking-wider">
                            {formatDate(eventDate)}
                          </h4>
                        </div>
                      )}
                      <motion.div 
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="flex gap-4 group"
                      >
                        <div className="w-16 shrink-0 text-right pt-1">
                          <div className="text-sm font-bold text-white/80">{formatTime(event.start.dateTime)}</div>
                          {event.end.dateTime && (
                            <div className="text-xs text-white/40">{formatTime(event.end.dateTime)}</div>
                          )}
                        </div>
                        <div className="w-px bg-white/10 relative">
                          <div className="absolute top-2 -left-1 w-2 h-2 rounded-full bg-indigo-500 ring-4 ring-[#141418]"></div>
                        </div>
                        <div className="flex-1 bg-white/5 border border-white/5 rounded-xl p-4 hover:bg-white/10 transition-colors">
                          <div className="flex justify-between items-start gap-4">
                            <h5 className="font-bold text-white">{event.summary || 'Busy'}</h5>
                            <a 
                              href={event.htmlLink} 
                              target="_blank" 
                              rel="noopener noreferrer"
                              className="opacity-0 group-hover:opacity-100 p-1.5 bg-white/5 hover:bg-white/10 rounded-lg text-white/60 hover:text-white transition-all"
                            >
                              <ExternalLink size={14} />
                            </a>
                          </div>
                        </div>
                      </motion.div>
                    </React.Fragment>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Tasks Sync Column */}
        <div className="space-y-6">
          <div className="bg-[#141418] border border-white/5 rounded-2xl p-6">
            <h3 className="text-xl font-bold mb-2">Sync Tasks</h3>
            <p className="text-sm text-white/40 mb-6">Push your pending tasks to your calendar to block out study time.</p>
            
            <div className="space-y-3 max-h-[500px] overflow-y-auto custom-scrollbar pr-2">
              {tasks.filter(t => !t.completed).length === 0 ? (
                <div className="text-center py-8 text-white/40 text-sm">
                  No pending tasks to sync.
                </div>
              ) : (
                tasks.filter(t => !t.completed).map(task => (
                  <div key={task.id} className="bg-white/5 border border-white/5 rounded-xl p-4 flex flex-col gap-3">
                    <div className="flex items-start gap-3">
                      <div className="mt-0.5 w-4 h-4 rounded-full border border-white/30 shrink-0"></div>
                      <span className="text-sm text-white/80 line-clamp-2">{task.text}</span>
                    </div>
                    <button
                      onClick={() => syncTaskToCalendar(task)}
                      disabled={!token}
                      className="w-full py-2 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-300 rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      <Plus size={14} />
                      Add to Calendar
                    </button>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ScheduleView;
